album* createnewalbum(album *head, char name[])
void addsongtoalbum(album *albumNode, song *newsong)
song* createSong(char *name, char *artist, int duration)
void viewallsongs(song* library)
void browsesong()
void playalbum(album *head)
void viewalbumsongs(album *head)
void deletesong(album *head)
void addSongToAlbum(album *head) 
void savealbumstofile(album *head)
